version: 2
jobs:
  java-build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run: ./gradlew clean build

  prepare-docker-build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run: ./.circleci/prepare_docker_build.sh

  docker-build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    steps:
      - checkout
      - run: ./.circleci/docker_build.sh

workflows:
  version: 2
  build-all:
    jobs:
      - java-build
      - prepare-docker-build:
          requires:
            - java-build
      - docker-build:
          requires:
            - prepare-docker-build