version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    steps:
      - checkout
      - run: ./gradlew clean build
      - run: ./.circleci/prepare_docker_build.sh
      - run: ./.circleci/docker_build.sh
      - run: sudo apt-get install python3 python3-pip
      - run: ./testing/test-all-internal.sh
      - run: ./testing/test-items-external.sh
