version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    steps:
      - checkout
      - run: java -version
      - run: ./gradlew clean build
      - run: ./.circleci/prepare_docker_build.sh
      - run: ./.circleci/docker_build.sh
