version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    steps:
      - checkout
      - run: curl -s "https://get.sdkman.io" | bash
      - run: source "$HOME/.sdkman/bin/sdkman-init.sh"
      - run: sdk use java 8.0.212-zulu
      - run: ./gradlew clean build
      - run: ./.circleci/prepare_docker_build.sh
      - run: ./.circleci/docker_build.sh
