version: 2.1
jobs:
  validate:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    steps:
      - checkout
      - run: ./gradlew clean build
      - run: ./.circleci/prepare_docker_build.sh
      - run: ./.circleci/docker_build.sh
      - run: ./testing/prepare-python.sh
      - run: ./testing/test-all-internal.sh
      - run: ./testing/test-items-external.sh
      - run: ./testing/test-stats-external.sh
      - run: ./testing/test-all-external.sh
      #todo store test results (see java example for circle)

  docker-push-snapshot:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    steps:
      - checkout
      - run: ./gradlew assertIsSnapshot
      - run: ./gradlew clean build
      #todo previous step can be faster when using cache
      - run: ./.circleci/prepare_docker_build.sh
      - run: ./.circleci/docker_build.sh
      - run: ./.circleci/push_docker_images.sh

  docker-push-release:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    steps:
      - checkout
      - run: ./gradlew assertIsRelease
      - run: ./gradlew clean build
      #todo previous step can be faster when using cache
      - run: ./.circleci/prepare_docker_build.sh
      - run: ./.circleci/docker_build.sh
      - run: ./.circleci/push_docker_images.sh

workflows:
  version: 2
  ci:
    jobs:
      - validate
      - docker-push-snapshot:
          requires:
            - validate
          context: DockerHub
          filters:
            branches:
              only: /\d+[.]\d+[.]\d+/
            tags:
              ignore: /.*/
      - docker-push-release:
          requires:
            - validate
          context: DockerHub
          filters:
            tags:
              only: /\d+[.]\d+[.]\d+/
            branches:
              ignore: /.*/