version: "3.5"

services:
  zookeeper:
    ports:
      - "2181:2181"

  kafka:
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    ports:
      - "29092:29092"